[build]
  publish = "src"
  edge_functions = "src/edge-functions"
[dev]
  publish = "src"
  edge_functions = "src/edge-functions"
[[redirects]]
  from = "/api/*"
  to = "/.netlify/edge-functions/netlify_index"
  status = 200
  force = true
[[redirects]]
  from = "/*"
  to = "/.netlify/edge-functions/netlify_index"
  status = 200
  force = true
